### ISSUE TITLE
S3: Support AWS Signature Version 4

### ISSUE THREAD

**Issue by krrrcks** [greghendershott/aws#36]
My AWS setup is located in Frankfurt. In that location for S3 the only supported authentication method is "v4". 

With the "standard installation" of this library I get a "The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256." error when doing anything on my S3 buckets (like "ls").

I am not familiar with all these details and couldn't get it from the source code. Is this new schema v4 supported..?

**Comment by greghendershott** [comment]
**Short version:** For now please use a bucket in a region that supports the v2 signature.

**Long version:**

[Amazon says here](http://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-authenticating-requests.html):

> Amazon S3 supports Signature Version 4, a protocol for authenticating inbound API requests to AWS services, in all AWS regions. At this time, existing AWS regions continue to support the previous protocol, Signature Version 2. Any new regions after January 30, 2014 will support only Signature Version 4 and therefore all requests to those regions must be made with Signature Version 4. Note that Signature Version 4 requires the request body to be signed for added security. This requirement creates additional computation load that is not required in Signature Version 2.

The library already supports the v4 sig in general; see sigv4.rkt. But s3.rkt does not use that. The wrinkle will be [signing the payload](http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-streaming.html) (which is n/a for v2 sig).

If all the older regions support v4 by now, and I can simply drop v2, that would help. Having both v2 and v4 as code paths that need testing... I'm not crazy about.

Although it's not rocket science I'll need a block of time to code and test this. But I'm already deep into a couple other projects right now. You're the only one to report this, so far, so it seems like there's not huge/urgent demand for this, yet. However if you can't use an older region (say for regulatory reasons), I would try to get to this sooner.

**Comment by krrrcks** [comment]
I understand. Well, I agree with you that supporting both versions does not pay off. I think I can move the data to a different region with v2 available.

**Comment by greghendershott** [comment]
@krrrcks 

1. Thank you for checking the availability of v4. That saves me the first step. :)

2. I'm glad the Ireland center is acceptable for now, and the library is working well with that.

3. I definitely do want to update this to use v4, as soon as I get a block of time to do it and test it thoroughly enough.

If anyone else comments on this thread to say they also need/want it, that would be helpful for me to know.

**Comment by krrrcks** [comment]
Yes, everything works smoothly so far. Thanks for the library. If you find time for this enhancement and have some code to test, just hit me up. I'll be glad to test.

**Comment by greghendershott** [comment]
Update: I've been working on this the last couple days. Bad news: Turned out to be an even bigger change than I expected. Good news: I think I have a handle on it.

I need to do more testing. Otherwise, my main concern is speed, due to the need to sign the payload.

For now I _think_ it will be acceptable for plain `put` to sign the entire payload up-front (_not_ to use the chunked transfer upload), because `multipart-put` is available and people ought to use that for larger payloads, anyway (because it's faster due to parallel uploading and it's recoverable). That is already "chunked".

So I think that's an acceptable way to avoid doing even more work than what I've already done. But I'm going to take at least a couple more days to test and to mull this over.

**Comment by krrrcks** [comment]
To me that sounds like a good approach.

**Comment by greghendershott** [comment]
@krrrcks Just wanted to touch base and let you know I haven't forgotten about this.

In fact I did end up going on to make the normal (non multipart) uploads use the "streaming"/chunked approach. Gory details in [commit message](https://github.com/greghendershott/aws/commit/54be58bdf6793f14a53c0fbc7bf2b8ad89305c3f).

That commit isn't yet merged to master. I'm going to mull it over a bit more. Also I may end up rebasing the WIP commits down to one or two clean commits for master.

**Comment by greghendershott** [comment]
Merged.

**Comment by krrrcks** [comment]
Wow, great! Thanks for implementing that feature so fast!
