### ISSUE TITLE
Are SimpleDB limit queries possible?

### ISSUE THREAD

**Issue by coopernurse** [greghendershott/aws#38]
First off, thanks for writing this library!

I'm using SimpleDb and wish to paginate through a domain.  It appears that the main `sdb` function automatically follows `NextToken` values in the response, which means the caller can't control the number of items that are returned.

Am I reading this correctly?  If so, I'd suggest making the "auto-next" behavior optional so the caller can control this.

I realize this changes the API a bit, so perhaps a new function is required.  If we do this then it would be nice to expose the consistent read flag as well.

I'm new to Racket but I would be happy to do a PR with this work - my main question is how we want to handle backwards compatibility.

**Comment by greghendershott** [comment]
I can't reply in detail today, but quickly: Yes -- you're correct, I'd welcome a PR, and I'd be glad to offer suggestions/guidance you want. I will try to follow up more tomorrow.

**Comment by coopernurse** [comment]
Hey there.  Thanks for the quick follow up.  I'm playing around with this now in my fork.

Would you suggest we introduce another 'select' function that has these extensions?  I'm realizing that the type of the return value needs to change.  Currently it's a list of items, but we may want to introduce a struct.  Perhaps something like:

```racket
(struct select-resp (items next-token meta))
(struct resp-meta (request-id box-usage))
```

If I get something working I'll push a branch to my fork and reference it here.  I would benefit from some code review -- there's a few concepts that are new to me, like contracts, so it may take a few iterations to get that dialed in.

Thanks

**Comment by greghendershott** [comment]
Hmm, actually: Are you sure SimpleDB supports doing this for `select`s?  Why I ask: I tried a query that returned several items. When I tried the same query but with `MaxNumberOfItems=1`, I got back just one item (as expected) but I did _not_ see any `NextToken` in the response.

(It's been a couple years since I worked with SimpleDB, and I only had time to try a few quick experiments. So maybe I made a dumb mistake.)

**Comment by greghendershott** [comment]
I'm doing some housekeeping on issues. I'm going to close this because IIUC it's not possible to do, and because I haven't back from you so I don't know if you even need/want this anymore.

However please feel free to let me know otherwise.
