### ISSUE TITLE
SDB: Support signature v4

### ISSUE THREAD

**Issue by greghendershott** [greghendershott/aws#43]

**Comment by krrrcks** [comment]
I am not using or plan to use the service; therefore this issue would be of low priority for me.

**Comment by greghendershott** [comment]
It appears that SDB doesn't support Signature v4. (Why? My guess: Although SDB continues to be supported it is deprecated in favor of Dynamo?)

I'll do some more searching to confirm. If this is correct, there is nothing to be done and I'll close this.

**Comment by krrrcks** [comment]
I searched a bit and found https://forums.aws.amazon.com/thread.jspa?threadID=96141&tstart=0 

Although there is no offical statement of AWS it seems that there is no further development on SDB. Therefore it is likely that they did not implement signature v4. As a conclusion I would second to close the ticket.

**Comment by greghendershott** [comment]
Thanks for checking! Closing this.

---

That leaves only #44 SES remaining to be done on the [Signature v4 milestone](https://github.com/greghendershott/aws/milestones/Signature%20v4). Although I don't feel any urgency to do Simple Email Service for its own sake, I might do it sooner for the sake of completing the entire milestone. :checkered_flag:  :)
