### ISSUE TITLE
SQS: How to handle received messages?

### ISSUE THREAD

**Issue by krrrcks** [greghendershott/aws#54]
Maybe this is a n00b question, but: How do I access the parts of a received message? The struct message is not provided to the requiring module as far as I see.

**Comment by greghendershott** [comment]
That looks like a dumb oversight. Would you like to add it?

**Comment by krrrcks** [comment]
I created a PR with a fix. I hope I have done everything right (I am not that experienced with Github).

**Comment by krrrcks** [comment]
Did you find time to review the fix? Would be great to have the struct provided in upstream.
