### ISSUE TITLE
`sign-uri` not documented?

### ISSUE THREAD

**Issue by mflatt** [greghendershott/aws#69]
When rendering, I get

```
raco setup: WARNING: undefined tag in <pkgs>/aws/aws/aws.scrbl:
raco setup:  ((lib "aws/s3.rkt") sign-uri)
```

It seems that ddeee9c2152f6aabaa55753fe8f4872088db060d added a reference to that name in the documentation.

Also, I was puzzled about the example that the documentation change referred to until I looked at the commit. Maybe the new example was supposed to be in the documentation, or maybe the documentation was meant to refer to the "examples" directory.

**Comment by greghendershott** [comment]
Sorry for the confusion; I guess I merged #68 too casually.

I thought the contributor meant for people to look at examples.rkt, which seemed acceptable-ish, but I didn't realize the undefined tag warning.

A minimal fix: change that `@racket` to a `@hyperlink` to the file, e.g. pointing here on github.

Better/ideally: move the contents of examples.rkt into the docs proper.

I'll one of those two things...
