### ISSUE TITLE
Add support for `Content-Disposition: inline` when using `put/file` with S3

### ISSUE THREAD

**Issue by priime0** [greghendershott/aws#70]
*Problem*:

Currently, `aws/s3` only supports providing `Content-Disposition: attachment; filename=somefile.txt`. This is hardcoded in `aws/s3`:

https://github.com/greghendershott/aws/blob/94c684d16e87547a0fda62e4ee2f9c68d9260ffc/aws/s3.rkt#L953-L956

So, whenever `put/file` is called, the file uploaded to S3 can only be retrieved as an attachment, prompting a download rather than opening the file inline.

`Content-Disposition` also supports an `inline` value that I would like to use that allows the file to be opened inline: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition

*Potential solution*:

Add an additional kwarg `#:inline? [inline? #f]` to `put/file` and `path->Content-Disposition`. Then, in `path->Content-Disposition`, return `"inline"` if `inline?`, otherwise return what is currently returned.

Defaulting `inline?` to `#f` maintains backwards-compatibility for the behaviour already implemented.

If you agree on the above solution, I can open a PR for the change.

**Comment by greghendershott** [comment]
<details>
<summary>Digression</summary>

It occurs to me now that the MIME type and disposition might be linked -- certain types (like text and html) are better handled inline, whereas most other types as attachments.

So I can imagine the existing `path => mime-type` hash-table becoming a `path => (cons mime-type inline?)`, to make both `Content-Type` and `Content-Disposition` headers. Or something like that.

But. I think that's over-complicating things. Especially for this library that's been around awhile, and I'm not eager to redesign. So...
</details>

Yes, the `#:inline?` optional keyword argument idea seems reasonable!

---

To be thorough, the PR should also:

- [ ] Add `#:inline?` also to `multipart-put/file`, which also calls `path->Content-Disposition`.
- [ ] Update `aws.scrbl` docs for both `put/file` and `multipart-put/file`.
- [ ] In the test submodule, add one new test of `path->Content-Disposition` for `#:inline? #t` (after the two existing tests).

If you're willing to do that, that would be great -- thanks in advance!
